spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdata?verifyServerCertificate=false&useSSL=false
    username: root
    password: saam1234
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 1000